stages:
  - quality
  - build
  - deploy
  - notification

variables:
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar" 
  GIT_DEPTH: "0" 

check compose:
  stage: quality
  only:
    variables:
      - $EXECUTAR == "deploy"
      - $EXECUTAR == "quality"
  tags:
    - shell
  script:
    - docker-compose config -q
    - echo $?

sonarcloud-check:
  tags:
    - docker
  stage: quality
  only:
    variables:
      - $EXECUTAR == "deploy"
      - $EXECUTAR == "quality"
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - sonar-scanner

build:
  stage: build
  tags:
    - shell
  only:
    variables:
      - $EXECUTAR == "deploy"
  script:
    - |
        if [ -e "/storage/wordpress/html" ]
        then
          echo "the directory exists"
          sudo rsync -avh --progress wordpress/* /storage/wordpress/html/
        else
          echo "the directory does not exist, let's deploy"
          sudo mkdir -p /storage/wordpress/html/
          sudo rsync -avh --progress wordpress/* /storage/wordpress/html/
        fi

deploy wordpress: &deploy
  stage: deploy
  tags:
    - shell
  only:
    variables:
      - $EXECUTAR == "deploy"
  script:
    - docker-compose down
    - sleep 10
    - docker-compose up -d

check deploy:
  <<: *deploy
  dependencies:
    - Deploy wordpress
  script:
    - sleep 10
    - curl -v http://localhost:8000
    - echo $?

notificat success: &notification
  stage: notification
  tags:
    - shell
  only:
    variables:
      - $EXECUTAR == "deploy"
  when: on_success
  script:
  - sh notificationSuccess.sh

notificat faild:
  <<: *notification
  when: on_failure
  script:
  - sh notificationFaild.sh
